# Generated by Django 4.2.7 on 2025-11-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
