# Generated by Django 4.2 on 2025-11-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0003_application_is_paid_application_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='student_portal.application')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Assignment',
                'verbose_name_plural': 'Application Assignments',
                'ordering': ['-assigned_date'],
                'unique_together': {('application', 'employee')},
            },
        ),
    ]
