# Generated by Django 4.2 on 2025-12-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0007_studentprofile_academic_qualifications_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
