# Generated by Django 4.2 on 2026-01-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0008_studentprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='application',
            name='mpesa_reference',
            field=models.CharField(blank=True, help_text='M-PESA transaction reference', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Employee notes about payment verification'),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_paid', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
