# Generated by Django 4.2 on 2026-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0009_remove_studentprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='payment_verification_date',
            new_name='payment_verified_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='mpesa_reference',
        ),
        migrations.AddField(
            model_name='application',
            name='mpesa_account_name',
            field=models.CharField(blank=True, help_text='Name on M-PESA account used for payment', max_length=150),
        ),
    ]
