# Generated by Django 4.2 on 2026-02-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0010_rename_payment_verification_date_application_payment_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('ordinary_level', 'Ordinary Level Certificate'), ('advanced_level', 'Advanced Level Certificate'), ('academic_transcript', 'Academic Transcript'), ('degree_certificate', 'Degree Certificate'), ('recommendation_letter', 'Recommendation Letter'), ('sop', 'Statement of Purpose'), ('cv', 'CV'), ('language_test', 'Language Test Results'), ('financial_documents', 'Financial Documents')], max_length=50),
        ),
    ]
