# Generated by Django 4.2 on 2025-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('nationality', models.CharField(default='Tanzanian', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('father_name', models.CharField(blank=True, max_length=150, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('olevel_school', models.CharField(blank=True, max_length=150, null=True)),
                ('olevel_country', models.CharField(default='Tanzania', max_length=100)),
                ('olevel_address', models.CharField(blank=True, max_length=255, null=True)),
                ('olevel_region', models.CharField(blank=True, max_length=100, null=True)),
                ('olevel_year', models.CharField(blank=True, max_length=10, null=True)),
                ('olevel_candidate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('olevel_gpa', models.CharField(blank=True, max_length=20, null=True)),
                ('alevel_school', models.CharField(blank=True, max_length=150, null=True)),
                ('alevel_country', models.CharField(default='Tanzania', max_length=100)),
                ('alevel_address', models.CharField(blank=True, max_length=255, null=True)),
                ('alevel_region', models.CharField(blank=True, max_length=100, null=True)),
                ('alevel_year', models.CharField(blank=True, max_length=10, null=True)),
                ('alevel_candidate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('alevel_gpa', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_country_1', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_country_2', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_country_3', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_country_4', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_program_1', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_program_2', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_program_3', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_program_4', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_name', models.CharField(max_length=150)),
                ('emergency_address', models.TextField()),
                ('emergency_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('emergency_relation', models.CharField(max_length=100)),
                ('heard_about_us', models.CharField(blank=True, max_length=100, null=True)),
                ('heard_about_other', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
