# Generated by Django 4.2 on 2025-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0002_studentapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
