# Generated by Django 4.2 on 2025-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0006_studentprofile_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='emergency_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
